common/models/AuthItem.php
<?php

namespace common\models;

use Yii; 
/**
 * This is the model class for table "{{%auth_item}}".
 *
 * @property string $name
 * @property integer $type
 * @property string $description
 * @property string $rule_name
 * @property string $data
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property AuthAssignment[] $authAssignments
 * @property AuthRule $ruleName
 * @property AuthItemChild[] $authItemChildren
 * @property AuthItemChild[] $authItemChildren0
 * @property AuthItem[] $children
 * @property AuthItem[] $parents
 */
class AuthItem extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%auth_item}}';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
                [['name', 'type'], 'required'],
                [['name'], 'unique'],
                [['type'], 'integer'],
                [['description', 'data'], 'string'],
                [['name', 'rule_name'], 'string', 'max' => 64],
                [['rule_name'], 'exist', 'skipOnError' => true, 'targetClass' => AuthRule::className(), 'targetAttribute' => ['rule_name' => 'name']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'name' => 'Name',
            'type' => 'Type',
            'description' => 'Description',
            'rule_name' => 'Rule Name',
            'data' => 'Data',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthAssignments() {
        return $this->hasMany(AuthAssignment::className(), ['item_name' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRuleName() {
        return $this->hasOne(AuthRule::className(), ['name' => 'rule_name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemChildren() {
        return $this->hasMany(AuthItemChild::className(), ['parent' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthItemChildren0() {
        return $this->hasMany(AuthItemChild::className(), ['child' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChildren() {
        return $this->hasMany(AuthItem::className(), ['name' => 'child'])->viaTable('{{%auth_item_child}}', ['parent' => 'name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParents() {
        return $this->hasMany(AuthItem::className(), ['name' => 'parent'])->viaTable('{{%auth_item_child}}', ['child' => 'name']);
    }

}

backend/controllers/AuthitemController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\AuthItem;
use common\models\AuthItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\CommonUtility;
use common\models\AuthItemChild;

/**
 * AuthitemController implements the CRUD actions for AuthItem model.
 */
class AuthitemController extends Controller {

    /**
     * @inheritdoc
     */
     public function behaviors() {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update','delete','assign','view'],
                'rules' => [
                       [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['backend.authitem.index'],
                    ],
                        [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['backend.authitem.create'],
                    ],
                     [
                        'actions' => ['update'],
                        'allow' => true,
                        'roles' => ['backend.authitem.update'],
                    ],
                     [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => ['backend.authitem.delete'],
                    ],
                    [
                        'actions' => ['view'],
                        'allow' => true,
                        'roles' => ['backend.authitem.view'],
                    ],
                    [
                        'actions' => ['assign'],
                        'allow' => true,
                        'roles' => ['backend.authitem.assign'],
                    ],
                ],
            ],  
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'delete' => ['POST'],
//                ],
//            ],
        ];
    }

    /**
     * Lists all AuthItem models.
     * @return mixed
     */
    public function actionAssign() {
        return $this->render('jstree');
    }

    public function actionDataset() {
        $items = CommonUtility::getItems([2]);
        $tree_items = [];

        foreach ($items as $key => $value) {
            $item_explode = "";
            $item_explode = explode(".", $value);
            if (count($item_explode) == 2) {
                $tree_items[$item_explode[0]][] = $item_explode[1];
            } else if (count($item_explode) == 3) {
                $tree_items[$item_explode[0]][$item_explode[1]][] = $item_explode[2];
            }
        }

        $array_for_json = '';
        foreach ($tree_items as $key => $value) {
            $tree_json_key = '';
            $tree_json_key["id"] = $key;
            $tree_json_key["text"] = ucfirst($key);
            $i = 0;
            foreach ($value as $key_child => $value_child) {

                if (is_array($value_child)) {

                    foreach ($value_child as $key_sub_child => $key_sub_value) {
                        $tree_json_key["children"][$i]["id"] = $key . "." . $key_child;
                        $tree_json_key["children"][$i]["text"] = ucfirst($key_child);
                        $tree_json_key["children"][$i]["children"][$key_sub_child]["id"] = $key . "." . $key_child . "." . $key_sub_value;
                        $tree_json_key["children"][$i]["children"][$key_sub_child]["text"] = ucfirst($key_sub_value);
                    }
                } else {
                    $tree_json_key["children"][$i]["id"] = $key . "." . $value_child;
                    $tree_json_key["children"][$i]["text"] = ucfirst($value_child);
                }
                $i++;
            }
            $array_for_json[] = $tree_json_key;
        }
        echo json_encode($array_for_json);
    }

    public function actionGetrolespermission() {
        if (isset($_POST['role_name'])) {
            $role_name = $_POST['role_name'];
        }
        if ($role_name) {
            $child_items = CommonUtility::getItemsByRoles($role_name);
            echo json_encode($child_items);
        } else {
            echo json_encode(['not found']);
        }
    }

    public function actionSetrolespermission() {
        $role_name = '';
        if (isset($_POST['role_name'])) {
            $role_name = trim($_POST['role_name']);
        }
        if ($role_name) {
            $all_items = $valid_items = $role_items = $insert_items = $remove_items = [];

            if (isset($_POST['permissions'])) {
                $permissions = $_POST['permissions'];
            }

            $all_items = CommonUtility::getItems(2);
            $valid_items = array_intersect($all_items, $permissions);
            $role_items = CommonUtility::getItemsByRoles($role_name);
            $insert_items = array_diff($valid_items, $role_items);
            $remove_items = array_diff($role_items, $valid_items);
            if (!empty($insert_items)) {
                $AuthItemChildModel = new AuthItemChild();
                foreach ($insert_items as $value) {
                    $rows[] = ['parent' => $role_name, 'child' => $value];
                }
                Yii::$app->db->createCommand()->batchInsert(AuthItemChild::tableName(), $AuthItemChildModel->attributes(), $rows)->execute();
            }
            foreach ($remove_items as $value) {
                Yii::$app->db->createCommand()->delete(AuthItemChild::tableName(), 'parent=:parent AND child=:child', [':parent' => $role_name, 'child' => $value])->execute();
            }
            echo json_encode(['done']);
        }
    }

    public function actionIndex() {
        $searchModel = new AuthItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AuthItem model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AuthItem model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new AuthItem();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AuthItem model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AuthItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AuthItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return AuthItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = AuthItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

backend/views/authitem/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="auth-item-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'type')->dropDownList([1 => "Role", 2 => "Item"], ['prompt' => '-Choose a Type-']); ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 1]) ?>

    <?php //$form->field($model, 'rule_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'data')->textarea(['rows' => 1]) ?>

    <?php //$form->field($model, 'created_at')->textInput() ?>

    <?php //$form->field($model, 'updated_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/authitem/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="auth-item-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'rule_name') ?>

    <?= $form->field($model, 'data') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/authitem/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = 'Create Auth Item';
$this->params['breadcrumbs'][] = ['label' => 'Auth Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/authitem/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AuthItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Auth Item';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-index">
    <p>
        <?= Html::a('Create Auth Item', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'name',
                [
                'attribute' => 'type',
                'value' => function($searchModel) {
                    return ($searchModel->type == 1) ? "Roles" : "Items";
                },
                'filter' => [1 => "Roles", 2 => "Items"]
            ],
            'description:ntext',
//            'rule_name',
            'data:ntext',
            // 'created_at',
            // 'updated_at',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);
    ?>
</div>

backend/views/authitem/jstree.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AuthAssignmentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Roles';
$this->params['breadcrumbs'][] = $this->title;
?>  
<?php
$this->registerCssFile(Yii::$app->request->baseUrl . "/../js/jstree/themes/default/style.min.css");
$this->registerJsFile(Yii::$app->request->baseUrl . "/../js/jstree/jstree.min.js", ['depends' => [\yii\web\JqueryAsset::className()]]);

$this->registerJs("
    $('p#message').hide();
    $('#ajax').jstree({
        'checkbox': {
            'keep_selected_style': false
        },
        'plugins': ['checkbox'],
        'core': {
            'data': {
                'url': '" . Url::toRoute(['authitem/dataset']) . "',
                'dataType': 'json'
            }
        }
    });
    
    $( '#target' ).click(function() {
     
    var selectedElmsIds = [];
        var selectedElms = $('#ajax').jstree('get_selected', true);
            $.each(selectedElms, function() {                 
            selectedElmsIds.push(this.id);
            });
    var role_name = $( '#role_name' ).val();        
        if(role_name =='')
        {
        alert('Please select a role');
        return false;
        }
        $.ajax({
        url: '" . Url::toRoute(['authitem/setrolespermission']) . "',
        type: 'POST',
        data: { permissions: selectedElmsIds ,role_name: role_name},
        dataType: 'json',
        success: function (result) {
        $('p#message').show();
            setTimeout(function() { $('p#message').hide(); }, 4000);
        },
        error: function (xhr, ajaxOptions, thrownError) {
        //alert(xhr.status);

        }
    }); 
       
});    

", yii\web\View::POS_END);

$this->registerJs("
    $( '#role_name' ).change(function() {
        var role_name = $(this).val();
    
        $.ajax({
        url: '" . Url::toRoute(['authitem/getrolespermission']) . "',
        type: 'POST',
        data: { role_name: role_name},
        dataType: 'json',
        success: function (result) {
            $('#ajax').jstree(true).deselect_all();
            $('#ajax').jstree('close_all');
              if(result =='not found')
            {
            }else{
            $('#ajax').jstree(true).select_node(result); 
                }
        },
        error: function (xhr, ajaxOptions, thrownError) {
        }
    });        
});    

", yii\web\View::POS_END);
?>
<div class="auth-assignment-index">
     
    <p id='message' style="font-size: 25px; font-weight: 600; color: green;">Update role success fully.</p>
    <?=
    Html::dropDownList('role_name', '', common\models\CommonUtility::getItems(1), ['prompt' => '-Choose a Role-', 'class' => "form-control", 'id' => 'role_name'])
    ?>
    <div id="ajax" class="demo"></div>
    <?= Html::Button('Submit', ['class' => 'btn btn-primary', 'id' => 'target']) ?>
</div>

backend/views/authitem/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = 'Update Auth Item: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Auth Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->name]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="auth-item-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/authitem/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\AuthItem */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Auth Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->name], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->name], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',  
            [
                'attribute' => 'type',
                'value' => ($model->type == 1) ? "Roles" : "Items",
            ],
            'description:ntext',
            'rule_name',
            'data:ntext',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>